apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-blue
  labels:
    app: bankapp
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
      version: blue
  template:
    metadata:
      labels:
        app: bankapp
        version: blue
    spec:
      containers:
      - name: bankapp
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
