apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-green
  labels:
    app: bankapp
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp
      version: green
  template:
    metadata:
      labels:
        app: bankapp
        version: green
    spec:
      containers:
      - name: bankapp
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
